### ISSUE TITLE
Add failback image as placeholder

### ISSUE THREAD

**Issue by dungdc40** [toilaken/doll#12]
![image](https://user-images.githubusercontent.com/9999109/120949790-7c8f5e80-c76f-11eb-8f64-a2b0e37e4095.png)

On product page, if there is no image link for product, or the link was broken, then should show place holder image (find some placeholder product image on google)

**Comment by dungdc40** [comment]
Still doesn't work, please use local image instead of remote one (save it to some folder inside backend/web/images)

**Comment by dungdc40** [comment]
Image link on home page was broken too

![image](https://user-images.githubusercontent.com/9999109/123533413-89381e80-d73f-11eb-89f1-500cc1bc6dfb.png)

**Comment by toilaken** [comment]
cái nè e làm rùi !
