### ISSUE TITLE
Add column 'note' to customer, product and order table

### ISSUE THREAD

**Issue by dungdc40** [toilaken/doll#19]
column name: note
type: text

For customer : note field will show on customer detail page, the same for product table
For order: add new page for order detail, show all information of order here (for example: backend/order/1 which show all info of order 1)

**Comment by dungdc40** [comment]
For order: allow to edit order, should be new url, example: backend/order/update/1,

For customer page, add Update button on each order, click on it will lead to order edit page
On order detail page, add Update button also

**Comment by toilaken** [comment]
cái nè e cx lm rồi
